const CandidateStatus = {
  APPLIED: "APPLIED",
  SCREENING: "SCREENING",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEWED: "INTERVIEWED",
  OFFERED: "OFFERED",
  CONFIRMED: "CONFIRMED",
  CONTRACT_PENDING_SIGNATURE: "CONTRACT_PENDING_SIGNATURE",
  CONTRACT_SIGNED: "CONTRACT_SIGNED",
  HIRED: "HIRED",
  REJECTED: "REJECTED",
  WITHDRAWN: "WITHDRAWN",
};

export default CandidateStatus;
