const CandidateStatus = {
  WAIT_FOR_INTERVIEW: "WAIT_FOR_INTERVIEW",
  REJECTED: "REJECTED",
  CONTRACT_NOT_YET_IN_FORCE: "CONTRACT_NOT_YET_IN_FORCE",
  HIRED: "HIRED",
  APPLIED: "APPLIED",
};

export default CandidateStatus;
