const UploadStrategy = {
  RESUME: "RESUME",
  CONTRACT_FILE: "CONTRACT_FILE",
  CONTRACT_TEMPLATE: "CONTRACT_TEMPLATE",
  CREW_RENTAL_REQUEST_DETAIL_FILE: "CREW_RENTAL_REQUEST_DETAIL_FILE",
  SHIP_IMAGE: "SHIP_IMAGE",
};
export default UploadStrategy;
