const UploadStrategy = {
  RESUME: "RESUME",
  CONTRACT_FILE: "CONTRACT_FILE",
  CONTRACT_TEMPLATE: "CONTRACT_TEMPLATE",
  CREW_RENTAL_REQUEST_DETAIL_FILE: "CREW_RENTAL_REQUEST_DETAIL_FILE",
  SHIP_IMAGE: "SHIP_IMAGE",
  COURSE_WALLPAPER: "COURSE_WALLPAPER",
  TRAINING_PROVIDER_LOGO: "TRAINING_PROVIDER_LOGO",
};
export default UploadStrategy;
