const Env = {
  BASE_API_URL: process.env.REACT_APP_BASE_API_URL,
  CLOUDINARY_API_KEY: process.env.REACT_APP_CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME: process.env.REACT_APP_CLOUDINARY_CLOUD_NAME,
};

export default Env;
